language: ruby
rvm:
  - 1.9.2
  - 1.9.3
  - ruby-head
gemfile:
  - gemfiles/3.2.gemfile
  - gemfiles/4.0.gemfile
matrix:
  exclude:
    - rvm: 1.9.2
      gemfile: gemfiles/4.0.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/4.0.gemfile

